name: Linting
run-name: Run ESLint and fix all auto-fixable errors

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Prepare Nuxt
        run: npm run prepare
        
      - name: Fix all auto-fixable errors
        id: fix-lint
        run: npm run lint:fix
